title : Probabilistic Thinking
author :
  name : itsuper7
  email : blah@email.test
  github : itsuper7
  twitter : 
  feedburner : feedname

navigation :
  - archive.html
  - categories.html
  - pages.html
  - Resource.html 
  - about.md
