* How To Prove that Exponential Kernel is a Positive Definite Kernel?

$k(x,z) = e^{-\alpha \|x-z \|}$

where \alpha > 0.

*solved*
One solution:
   [[http://math.stackexchange.com/questions/248976/how-to-prove-that-exponential-kernel-is-positive-definite/249343#249343][mathematics]]
1. Firstly, prove $\phi(r) = e^{-\alpha y^{\frac{1}{2}}}$ is completely monotone on [0, \infty)
2. Use Schoenberg interpolation theorem. [[http://www.math.iit.edu/~fass/603_ch2.pdf][pdf]]


A interesting theorem is Hausdorff-Bernstein-Widder Theorem, which states
completely monotone function is equivalent to Laplace transform of a finite non-negative 
Borel measure u on [0,\infty].  
 Thus $\phi(r)$ is of the form
 \begin{equation}
\phi(r) = \mathcal{L}u(r) = \int_{0}^{\infty} e^{-rt} du(t).
 \end{equation} 
* How to Prove that Exponential $\chi^{2}$ kernel is a Valid Kernel?

\begin{equation} 
\begin{split}
k(x,z) &= e^{- \chi(x,z)^{2}}\\
\chi(x,z) &= \sum_{i}^{d} \frac{(x_{i} - z_{i})^{2}}{x_{i} + z_{i}}
\end{split}
\end{equation}

*solved*
One Solution:
\begin{equation} 
\begin{split}
\chi(x,z) = &= \sum_{i}^{d} \frac{(x_{i} - z_{i})^{2}}{x_{i} + z_{i}}\\
&= \sum_{i}^{d} x_{i} + z_{i} - 4*\frac{x_{i}*z_{i}}{x_{i} + z_{i}} 
\end{split}
\end{equation}

let k(x,z) = $\frac{2xz}{x + z}$, $\Delta = log(z) - log(x)$
\begin{equation} 
\begin{split}
k(x,z) &= \sqrt{xz} \frac{2}{\sqrt{\frac{x}{z}} + \sqrt{\frac{z}{x}}} \\
&=\sqrt{xz}sech(\frac{\Delta}{2})
\end{split}
\end{equation}

The Fourier transform of sech(x) is $\pi sech(\pi \omega)$(non-unitary, angular frequency).
Using the inverse Fourier transform, 

\begin{equation} 
\begin{split}
k(x,z) &= \sqrt{xz} \int_{-\infty}^{\infty} e^{i\omega(log(x) - log(z))}sech(\pi \omega) d \omega
&= \int_{-\infty}^{\infty} \Phi_{\omega}(x) * \Phi_{\omega}(z) d \omega
\end{split}
\end{equation}


